name: CI

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: npm install
    - name: test
      run: npm run test
      env:
        CI: true
    - name: lint
      run: npm run lint
      env:
        CI: true
